version: 2.1
parameters:
  image-name:
    type: string
    default: "alpine"
  image-tag:
    type: string
    default: "3.8"
jobs:
  build:
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - run: docker pull ${image-name}:${image-tag}
      - run:
          name: "Pull and Scan"
          command: 
            wget https://community-aqua-reports.s3.amazonaws.com/scannercli && 
            chmod +x scannercli &&
            mkdir /tmp/artifacts &&
            sudo mkdir /opt/aquascans &&
            sudo chmod 777 /opt/aquascans &&
            ./scannercli scan --host $AQUA_SERVER --local ${image-name}:${image-tag} --dockerless --user $AQUA_USER --password $AQUA_PWD --htmlfile /tmp/artifacts/${image-name}-${image-tag}.html
      - store_artifacts:
          path: /tmp/artifacts
          