version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    #environment:
     # REPO: "https://github.com/BryanKMorrow/aqua-reports.git"
    #  IMAGE: "aqua-reports"
    #  TAG: "latest"
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: "Checkout and Build Code"
          command:
          #  git clone ${REPO};
          #  cd aqua-reports;
            docker build -f Dockerfile -t ${IMAGE}:${TAG} .
      - run:
          name: "Pull and Scan"
          command:
            wget https://community-aqua-reports.s3.amazonaws.com/scannercli &&
            chmod +x scannercli &&
            mkdir /tmp/artifacts &&
            sudo mkdir /opt/aquascans &&
            sudo chmod 777 /opt/aquascans &&
            ./scannercli scan --host $AQUA_SERVER --local ${IMAGE}:${TAG} --dockerless --user $AQUA_USER --password $AQUA_PWD 
            # --htmlfile /tmp/artifacts/${IMAGE}-${TAG}.html
     # - store_artifacts:
    #      path: /tmp/artifacts

