# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
#/version: 2.1
# Use a package of configuration called an orb.
#orbs:
  # Declare a dependency on the welcome-orb
#  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
#workflows:
  # Name the workflow "welcome"
 # welcome:
    # Run the welcome/run job in its own container
 #   jobs:
 #     - welcome/run    
version: 2.1
jobs:
  build:
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - setup_remote_docker:
          version: 18.06.0-ce
    # Install via apk on alpine based images
    #  - run:
    #      name: Install Docker client
    #      command: apk add docker-cli
      - run: |
          docker login registry.aquasec.com -U $AQUA_USERNAME -P $AQUA_PASSWORD
          docker pull registry.aquasec.com/scanner:4.6
          docker run -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:4.6 scan -H http://aquasec-demo1082-vm0.eastus.cloudapp.azure.com/#/dashboard:8080 -U $LOGIN_USERNAME -P $LOGIN_PASSWORD --local alpine:3.7
